import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { VIEWER_CONFIG } from "./ViewerConfig";
import { disposeObject } from "../core/runtime/dispose";
import type { PBRConfig } from "../core/domain/vehicle";
import { GlbAnalyzer } from "./GlbAnalyzer";
import type { VehicleCapabilities } from "../core/domain/vehicleCapabilities";
import { EMPTY_VEHICLE_CAPABILITIES } from "../core/domain/vehicleCapabilities";

export interface LoadedVehicleAsset {
  url: string;
  pivot: THREE.Group;
  meshes: THREE.Mesh[];
  meshMap: Map<string, THREE.Mesh>;
  /** Map of GLB material name → all mesh instances that use it */
  materialNameIndex: Map<string, THREE.Mesh[]>;
  mixer: THREE.AnimationMixer | null;
  /** Dynamically discovered customization capabilities — generated by GlbAnalyzer */
  capabilities: VehicleCapabilities;
}

interface OriginalMaterialState {
  colorHex: number;
  roughness: number;
  metalness: number;
  opacity: number;
  transparent: boolean;
  wireframe: boolean;
  emissiveHex: number;
  emissiveIntensity: number;
}

/** Original material states keyed by GLB material name (not mesh name) */
type OriginalByMaterialName = Map<string, OriginalMaterialState>;

export class AssetManager {
  private loader: GLTFLoader;
  private cache = new Map<string, LoadedVehicleAsset>();
  private inflight = new Map<string, Promise<LoadedVehicleAsset>>();
  private current: LoadedVehicleAsset | null = null;
  private maxAnisotropy: number;

  /** Original states per GLB material name — set once on load, never mutated */
  private originalsByMaterialName: OriginalByMaterialName = new Map();

  constructor(renderer: THREE.WebGLRenderer) {
    this.maxAnisotropy = Math.min(8, renderer.capabilities.getMaxAnisotropy());
    this.loader = new GLTFLoader();
  }

  get currentAsset() {
    return this.current;
  }

  prefetch(url: string) {
    if (this.cache.has(url) || this.inflight.has(url)) return;
    void fetch(url, { priority: "low" } as RequestInit).catch(() => {});
  }

  // ── Per-mesh reset (used by legacy mesh-name flow) ──────────────────────────
  resetMaterials(asset: LoadedVehicleAsset) {
    asset.meshes.forEach((mesh) => {
      const orig = mesh.userData.originalMaterial as OriginalMaterialState | undefined;
      if (orig) {
        this.forEachMaterial(mesh, (material) => {
          if (material instanceof THREE.MeshStandardMaterial) {
            material.color.setHex(orig.colorHex);
            material.roughness = orig.roughness;
            material.metalness = orig.metalness;
            material.opacity = orig.opacity;
            material.transparent = orig.transparent;
            material.wireframe = orig.wireframe;
            material.emissive.setHex(orig.emissiveHex);
            material.emissiveIntensity = orig.emissiveIntensity;
            material.needsUpdate = true;
          }
        });
      }
    });
  }

  // ── Semantic material-name-based reset ──────────────────────────────────────
  /**
   * Resets all materials to their original GLB state.
   * This is the correct "Reset Customization" entry point —
   * it restores exactly the original GLB appearance without reloading.
   */
  resetAllToOriginal() {
    if (!this.current) return;
    this.current.materialNameIndex.forEach((meshes, materialName) => {
      const orig = this.originalsByMaterialName.get(materialName);
      if (!orig) return;
      for (const mesh of meshes) {
        this.forEachMaterial(mesh, (material) => {
          if (material instanceof THREE.MeshStandardMaterial) {
            material.color.setHex(orig.colorHex);
            material.roughness = orig.roughness;
            material.metalness = orig.metalness;
            material.opacity = orig.opacity;
            material.transparent = orig.transparent;
            material.wireframe = orig.wireframe;
            material.emissive.setHex(orig.emissiveHex);
            material.emissiveIntensity = orig.emissiveIntensity;
            material.needsUpdate = true;
          }
        });
      }
    });
  }

  // ── Semantic material-name-based update ────────────────────────────────────
  /**
   * Applies a PBRConfig to ALL meshes that share the given GLB material name.
   * This is the correct customization entry point — never mutates shared materials globally.
   * Each mesh already has an independent cloned material instance (cloned during parse).
   */
  updateMaterialByName(materialName: string, config: PBRConfig) {
    if (!this.current) return;
    const meshes = this.current.materialNameIndex.get(materialName);
    if (!meshes || meshes.length === 0) return;

    for (const mesh of meshes) {
      this.forEachMaterial(mesh, (material) => {
        if (material instanceof THREE.MeshStandardMaterial) {
          if (config.color !== undefined) material.color.set(config.color);
          if (config.roughness !== undefined) material.roughness = config.roughness;
          if (config.metalness !== undefined) material.metalness = config.metalness;
          if (config.opacity !== undefined) {
            material.opacity = config.opacity;
            material.transparent = config.opacity < 1;
          }
          if (config.transparent !== undefined) material.transparent = config.transparent;
          if (config.wireframe !== undefined) material.wireframe = config.wireframe;
          if (config.emissive !== undefined) material.emissive.set(config.emissive);
          if (config.emissiveIntensity !== undefined) material.emissiveIntensity = config.emissiveIntensity;

          // Clearcoat only on MeshPhysicalMaterial (which extends MeshStandardMaterial)
          if (material instanceof THREE.MeshPhysicalMaterial) {
            if (config.clearcoat !== undefined) material.clearcoat = config.clearcoat;
            if (config.clearcoatRoughness !== undefined) material.clearcoatRoughness = config.clearcoatRoughness;
          }

          material.needsUpdate = true;
        }
      });
    }
  }

  /**
   * Returns a snapshot of all GLB material names discovered in the current asset.
   * Useful for the UI to know which customization categories are available.
   */
  getMaterialInventory(): string[] {
    if (!this.current) return [];
    return Array.from(this.current.materialNameIndex.keys());
  }

  // ── Legacy per-mesh-name update (used by Part Inspector click flow) ─────────
  updateMaterial(meshName: string, config: { color?: string; roughness?: number; metalness?: number; opacity?: number; wireframe?: boolean }) {
    if (!this.current) return;
    const mesh = this.current.meshMap.get(meshName);
    if (!mesh) return;

    this.forEachMaterial(mesh, (material) => {
      if (material instanceof THREE.MeshStandardMaterial) {
        if (config.color !== undefined) material.color.set(config.color);
        if (config.roughness !== undefined) material.roughness = config.roughness;
        if (config.metalness !== undefined) material.metalness = config.metalness;
        if (config.opacity !== undefined) {
          material.opacity = config.opacity;
          material.transparent = config.opacity < 1;
        }
        if (config.wireframe !== undefined) material.wireframe = config.wireframe;
        material.needsUpdate = true;
      }
    });
  }

  // ── Load ────────────────────────────────────────────────────────────────────
  async load(url: string, onProgress?: (progress: number) => void): Promise<LoadedVehicleAsset> {
    const cached = this.cache.get(url);
    if (cached) {
      this.cache.delete(url);
      this.cache.set(url, cached);
      onProgress?.(1);
      this.resetMaterials(cached);
      this.current = cached;
      // Rebuild original-by-name map from cache
      this.rebuildOriginalsMap(cached);
      return cached;
    }

    const pending = this.inflight.get(url) ?? this.parse(url, onProgress);
    this.inflight.set(url, pending);
    try {
      const asset = await pending;
      this.cache.set(url, asset);
      this.resetMaterials(asset);
      this.current = asset;
      this.rebuildOriginalsMap(asset);
      return asset;
    } finally {
      this.inflight.delete(url);
    }
  }

  private rebuildOriginalsMap(asset: LoadedVehicleAsset) {
    this.originalsByMaterialName.clear();
    asset.materialNameIndex.forEach((meshes, materialName) => {
      // Use the first mesh's material as the representative original
      const firstMesh = meshes[0];
      if (!firstMesh) return;
      const orig = firstMesh.userData.originalMaterial as OriginalMaterialState | undefined;
      if (orig) {
        this.originalsByMaterialName.set(materialName, orig);
      }
    });
  }

  private async parse(url: string, onProgress?: (progress: number) => void): Promise<LoadedVehicleAsset> {
    const gltf = await this.loader.loadAsync(url, (event) => {
      if (event.total > 0) onProgress?.(event.loaded / event.total);
    });

    const model = gltf.scene;

    // Verified GLB Coordinate System: Model is natively Y-UP!
    model.rotation.set(0, 0, 0);
    model.updateMatrixWorld(true);

    // Calculate bounding box in canonical upright orientation
    const box = new THREE.Box3().setFromObject(model);
    const size = box.getSize(new THREE.Vector3());

    const maxDim = Math.max(size.x, size.y, size.z, 0.001);
    const scale = VIEWER_CONFIG.FIT_SIZE / maxDim;

    model.scale.setScalar(scale);
    model.updateMatrixWorld(true);

    // Recompute box after scaling to position wheels precisely on Y = 0
    const scaledBox = new THREE.Box3().setFromObject(model);
    const scaledCenter = scaledBox.getCenter(new THREE.Vector3());

    model.position.x = -scaledCenter.x;
    model.position.z = -scaledCenter.z;
    model.position.y = -scaledBox.min.y; // Lowest point of wheels sits at Y = 0

    const pivot = new THREE.Group();
    pivot.name = "vehicle-pivot";
    pivot.add(model);

    const meshes: THREE.Mesh[] = [];
    const meshMap = new Map<string, THREE.Mesh>();
    // materialNameIndex: materialName → all meshes using that material
    const materialNameIndex = new Map<string, THREE.Mesh[]>();

    model.traverse((child) => {
      if (!(child instanceof THREE.Mesh)) return;

      // Clone material so every mesh node has a unique, independent material instance.
      // This is critical: it means updateMaterialByName can target all meshes sharing
      // a semantic group without accidentally cross-contaminating other parts.
      if (Array.isArray(child.material)) {
        child.material = child.material.map((mat) => mat.clone());
      } else if (child.material) {
        child.material = child.material.clone();
      }

      meshes.push(child);
      if (child.name) {
        meshMap.set(child.name, child);
      }

      child.frustumCulled = false;
      child.castShadow = false;
      child.receiveShadow = false;

      this.forEachMaterial(child, (material) => {
        material.depthTest = true;
        material.depthWrite = true;

        if (material instanceof THREE.MeshStandardMaterial) {
          // Capture original GLB material properties per mesh (for per-mesh reset)
          if (!child.userData.originalMaterial) {
            child.userData.originalMaterial = {
              colorHex: material.color.getHex(),
              roughness: material.roughness,
              metalness: material.metalness,
              opacity: material.opacity,
              transparent: material.transparent,
              wireframe: material.wireframe,
              emissiveHex: material.emissive.getHex(),
              emissiveIntensity: material.emissiveIntensity ?? 0,
            } satisfies OriginalMaterialState;
          }

          // Index this mesh under its material name
          const matName = material.name;
          if (matName) {
            if (!materialNameIndex.has(matName)) {
              materialNameIndex.set(matName, []);
            }
            materialNameIndex.get(matName)!.push(child);
          }

          material.roughness = THREE.MathUtils.clamp(material.roughness ?? 0.5, 0.05, 0.95);
          material.envMapIntensity = 0.85;

          if (material.map) material.map.colorSpace = THREE.SRGBColorSpace;
          if (material.normalMap) material.normalScale.multiplyScalar(0.75);

          for (const map of [
            material.map,
            material.normalMap,
            material.roughnessMap,
            material.metalnessMap,
            material.aoMap,
            material.emissiveMap,
          ]) {
            if (!map) continue;
            map.anisotropy = this.maxAnisotropy;
            map.generateMipmaps = true;
            map.minFilter = THREE.LinearMipmapLinearFilter;
            map.magFilter = THREE.LinearFilter;
            map.needsUpdate = true;
          }
        }
        material.needsUpdate = true;
      });
    });

    let mixer: THREE.AnimationMixer | null = null;
    if (gltf.animations.length) {
      mixer = new THREE.AnimationMixer(model);
      gltf.animations.forEach((clip) => mixer?.clipAction(clip).play());
    }

    // Build the preliminary asset so the analyzer can iterate its meshes
    const partialAsset = { url, pivot, meshes, meshMap, materialNameIndex, mixer, capabilities: EMPTY_VEHICLE_CAPABILITIES };

    // Run the analyzer synchronously — it only reads material state, doesn't mutate anything
    const capabilities = GlbAnalyzer.analyze(partialAsset);

    return { ...partialAsset, capabilities };
  }

  forEachMaterial(mesh: THREE.Mesh, fn: (material: THREE.Material) => void) {
    const materials = Array.isArray(mesh.material) ? mesh.material : [mesh.material];
    materials.forEach(fn);
  }

  /** Returns the capability report for the current asset, or null if nothing loaded */
  getCapabilities() {
    return this.current?.capabilities ?? null;
  }

  release(asset: LoadedVehicleAsset | null = this.current) {
    if (!asset) return;
    asset.mixer?.stopAllAction();
    asset.pivot.removeFromParent();
    if (asset === this.current) this.current = null;
  }

  dispose() {
    this.release();
    this.cache.forEach((asset) => {
      asset.mixer?.stopAllAction();
      asset.pivot.removeFromParent();
      disposeObject(asset.pivot);
    });
    this.cache.clear();
    this.originalsByMaterialName.clear();
  }
}
