import { create } from "zustand";
import type { PartMaterialConfig, VehiclePartData, ViewPreset, PartCategory } from "../domain/vehicle";
import type { VehicleCustomization } from "../domain/vehicleCustomization";
import { DEFAULT_VEHICLE_CUSTOMIZATION } from "../domain/vehicleCustomization";
import type { VehicleCapabilities } from "../domain/vehicleCapabilities";
import { EMPTY_VEHICLE_CAPABILITIES } from "../domain/vehicleCapabilities";

// ─────────────────────────────────────────────────────────────────────────────
// Legacy VEHICLE_PARTS_DATA — kept only for the Part Inspector click flow.
// These are NOT used for the semantic customization system.
// The real mesh names are discovered dynamically from the loaded GLB.
// ─────────────────────────────────────────────────────────────────────────────
export const VEHICLE_PARTS_DATA: VehiclePartData[] = [];

// ─────────────────────────────────────────────────────────────────────────────
// Infer category from raw GLB mesh names (fallback for unknown meshes)
// ─────────────────────────────────────────────────────────────────────────────
function inferCategoryFromMeshName(meshName: string): PartCategory {
  const lower = meshName.toLowerCase();
  if (lower.includes("wheel") || lower.includes("tire") || lower.includes("rim") || lower.includes("hub") || lower.includes("cap")) return "WHEELS";
  if (lower.includes("seat") || lower.includes("dash") || lower.includes("steering") || lower.includes("cockpit") || lower.includes("interior")) return "COCKPIT";
  if (lower.includes("engine") || lower.includes("valve") || lower.includes("exhaust") || lower.includes("power")) return "POWER";
  if (lower.includes("chassis") || lower.includes("frame") || lower.includes("rail") || lower.includes("floor")) return "CHASSIS";
  return "BODY";
}

export function getPartByMeshName(meshName: string | null): VehiclePartData | null {
  if (!meshName) return null;
  return {
    id: meshName.toLowerCase().replace(/_/g, "-").replace(/\s+/g, "-"),
    name: meshName.replace(/_/g, " "),
    category: inferCategoryFromMeshName(meshName),
    meshName: meshName,
    description: `Selected GLB component: ${meshName.replace(/_/g, " ")}. Adjust material finish, paint color, roughness, metalness below.`,
    specs: { "Node ID": meshName, Status: "Active Mesh" },
    defaultMaterial: {
      color: "#888888",
      roughness: 0.4,
      metalness: 0.5,
      opacity: 1,
      transparent: false,
      wireframe: false,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Store interface
// ─────────────────────────────────────────────────────────────────────────────
interface VehicleState {
  selectedVehicleId: string;
  selectedMeshName: string | null;
  selectedPart: VehiclePartData | null;
  hoveredMeshName: string | null;

  /**
   * Per-mesh fine-grained overrides — set by the Part Inspector click flow.
   * Separate from the semantic vehicleCustomization state.
   */
  materialOverrides: Record<string, Partial<PartMaterialConfig>>;

  /**
   * The primary semantic customization state — plain serializable JSON.
   * No Three.js objects live here.
   */
  vehicleCustomization: VehicleCustomization;

  /**
   * Capability report generated by GlbAnalyzer for the currently loaded asset.
   * null until the first model finishes loading.
   * Drives which sections the CustomizePanel renders.
   */
  vehicleCapabilities: VehicleCapabilities;

  activeTool: string | null;
  autoRotate: boolean;
  activeViewPreset: ViewPreset;
  availableMeshNames: string[];
  /** @deprecated Use vehicleCapabilities.allMaterials instead */
  materialInventory: string[];

  setSelectedVehicleId: (id: string) => void;
  setAvailableMeshNames: (names: string[]) => void;
  setMaterialInventory: (names: string[]) => void;
  setVehicleCapabilities: (caps: VehicleCapabilities) => void;
  setSelectedMesh: (meshName: string | null) => void;
  setHoveredMesh: (meshName: string | null) => void;
  updatePartMaterial: (meshName: string, config: Partial<PartMaterialConfig>) => void;
  setMaterialOverrides: (overrides: Record<string, Partial<PartMaterialConfig>>) => void;

  /** Update the semantic customization state (partial merge) */
  setVehicleCustomization: (c: Partial<VehicleCustomization>) => void;
  /** Reset the semantic customization state to defaults */
  resetVehicleCustomization: () => void;

  setActiveTool: (tool: string | null) => void;
  setAutoRotate: (enabled: boolean) => void;
  setPresetView: (preset: ViewPreset) => void;
}

// ─────────────────────────────────────────────────────────────────────────────
// Store implementation
// ─────────────────────────────────────────────────────────────────────────────
export const useVehicleStore = create<VehicleState>((set) => ({
  selectedVehicleId: "electric-hatch-05",
  selectedMeshName: null,
  selectedPart: null,
  hoveredMeshName: null,
  materialOverrides: {},
  vehicleCustomization: DEFAULT_VEHICLE_CUSTOMIZATION,
  vehicleCapabilities: EMPTY_VEHICLE_CAPABILITIES,
  activeTool: null,
  autoRotate: false,
  activeViewPreset: "side",
  availableMeshNames: [],
  materialInventory: [],

  setSelectedVehicleId: (id) => set({ selectedVehicleId: id }),
  setAvailableMeshNames: (names) => set({ availableMeshNames: names }),
  setMaterialInventory: (names) => set({ materialInventory: names }),
  setVehicleCapabilities: (caps) => set({ vehicleCapabilities: caps }),

  setSelectedMesh: (meshName) =>
    set(() => {
      if (!meshName) return { selectedMeshName: null, selectedPart: null };
      const part = getPartByMeshName(meshName);
      return { selectedMeshName: meshName, selectedPart: part };
    }),

  setHoveredMesh: (meshName) => set({ hoveredMeshName: meshName }),

  updatePartMaterial: (meshName, config) =>
    set((state) => ({
      materialOverrides: {
        ...state.materialOverrides,
        [meshName]: {
          ...(state.materialOverrides[meshName] || {}),
          ...config,
        },
      },
    })),

  setMaterialOverrides: (overrides) => set({ materialOverrides: overrides }),

  setVehicleCustomization: (c) =>
    set((state) => ({
      vehicleCustomization: deepMerge(state.vehicleCustomization, c),
    })),

  resetVehicleCustomization: () =>
    set({ vehicleCustomization: DEFAULT_VEHICLE_CUSTOMIZATION }),

  setActiveTool: (tool) => set({ activeTool: tool }),
  setAutoRotate: (enabled) => set({ autoRotate: enabled }),
  setPresetView: (preset) => set({ activeViewPreset: preset }),
}));

// ─────────────────────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────────────────────

/** Shallow-merge top-level keys but deep-merge nested objects one level */
function deepMerge<T extends object>(base: T, patch: Partial<T>): T {
  const result = { ...base };
  for (const key in patch) {
    const patchVal = patch[key];
    const baseVal = base[key];
    if (patchVal !== undefined && typeof patchVal === "object" && !Array.isArray(patchVal) && typeof baseVal === "object") {
      (result as Record<string, unknown>)[key] = { ...(baseVal as object), ...(patchVal as object) };
    } else if (patchVal !== undefined) {
      (result as Record<string, unknown>)[key] = patchVal;
    }
  }
  return result;
}

function areConfigsEqual(
  c1: Partial<PartMaterialConfig> = {},
  c2: Partial<PartMaterialConfig> = {}
): boolean {
  const keys: (keyof PartMaterialConfig)[] = [
    "color",
    "roughness",
    "metalness",
    "opacity",
    "transparent",
    "wireframe",
  ];
  for (const k of keys) {
    if (c1[k] !== c2[k]) return false;
  }
  return true;
}

export function isOverridesDirty(
  current: Record<string, Partial<PartMaterialConfig>> = {},
  saved: Record<string, Partial<PartMaterialConfig>> = {}
): boolean {
  const allMeshNames = Array.from(
    new Set([...Object.keys(current), ...Object.keys(saved)])
  );
  for (const meshName of allMeshNames) {
    if (!areConfigsEqual(current[meshName], saved[meshName])) {
      return true;
    }
  }
  return false;
}

export function isCustomizationDirty(
  current: VehicleCustomization,
  saved: VehicleCustomization
): boolean {
  return JSON.stringify(current) !== JSON.stringify(saved);
}
